### ISSUE TITLE
Prometheus sink: Out of bounds metrics

### ISSUE THREAD

**Issue by spencergilbert** [timberio/vector#5744] opened 2020-12-28 17:33 UTC
### Vector Version

```
Dec 27 21:43:30.726 INFO vector: Vector has started. version="0.12.0" git_version="v0.11.0-197-gbbb5fb6" released="Sun, 27 Dec 2020 04:54:32 +0000" arch="x86_64"
Sun, Dec 27 2020 4:43:30 pm
```

### Vector Configuration File

```toml
# ------------------------------------------------------------------------------
# Metric events
# ------------------------------------------------------------------------------

[sources.internal_metrics]
type = "internal_metrics"

[sinks.prometheus]
type = "prometheus_exporter"
inputs = ["internal_metrics"]
address = "0.0.0.0:9090"
```

I recently noticed "all" of my vector metrics were not being recorded by prometheus, though the scrapes were marked as successful (there are very brief periods when metrics are present, seems like right around vector startup). When moving prometheus's log level to debug I see the following messages:

```
level=debug ts=2020-12-28T17:21:15.093Z caller=scrape.go:1255 component="scrape manager" scrape_pool=vector/vector-agent/0 target=http://10.42.2.152:9090/metrics msg="Out of bounds metric" series="node_cpu_seconds_total{collector=\"cpu\",cpu=\"23\",host=\"vector-agent-f97wn\",mode=\"nice\"}"
```
(Similar messages for all other varieties of vector's metrics, all with the same `msg`)

I haven't run into this with prometheus before, so I'm not entirely sure where to start, but I can help narrow down when this started happening by deploying specific releases until it's resolved.

**Comment by spencergilbert** [comment] 2020-12-28 17:59
Example of an internal_metric:
```
level=debug ts=2020-12-28T17:41:34.644Z caller=scrape.go:1255 component="scrape manager" scrape_pool=vector/vector-agent/0 target=http://10.42.0.34:9090/metrics msg="Out of bounds metric" series="vector_files_added_total{component_kind=\"source\",component_name=\"kubernetes_logs\",component_type=\"kubernetes_logs\",file=\"/var/log/pods/aqua_aqua-server-console-5d48bb68c5-kzmhw_c173c2b7-8536-4476-ada1-0ba9eadc223f/web/1339.log\"}"
```

Curling for the `node_cpu_seconds_total` metric
```
❯ curl -s localhost:9090/metrics | rg "cpu_seconds_total" | rg "nice" | rg 'cpu="23"'
node_cpu_seconds_total{collector="cpu",cpu="23",host="vector-agent-f97wn",mode="nice"} 22.99 1608565731999
```

**Comment by jszwedko** [comment] 2020-12-28 18:07
I did some initial investigation into this and it seems like it'd be related to the timestamp based on

https://github.com/prometheus/prometheus/blob/4eca4dffb89d9da927f1e7884efe85cbd6dc30f3/scrape/target.go#L325-L327

Notably I was able to setup a local prometheus to scrape this fine:

```
prometheus, version 2.23.0 (branch: HEAD, revision: 26d89b4b0776fe4cd5a3656dfa520f119a375273)
  build user:       root@37609b3a0a21
  build date:       20201126-10:56:17
  go version:       go1.15.5
  platform:         linux/amd64
```

I did note, however, that the timestamps for the metrics appear to be roughly 15 minutes in the past, which I did not expect.

I was using this config:

```
[sources.in]
  type = "host_metrics"

[sinks.out]
  type = "prometheus"
  inputs = ["in"]
  address = "0.0.0.0:9598" # required
```

**Comment by jszwedko** [comment] 2020-12-28 18:37
I realized it looks like the metric timestamps are never updating. I reran later, and saw the timestamp 24 minutes behind the current.

**Comment by jszwedko** [comment] 2020-12-28 18:48
@jamtur01 @binarylogic just noting that this is a regression from 0.11.1 (which didn't include the timestamp in the metric output) so we should make sure it gets fixed before another release.

**Comment by jszwedko** [comment] 2021-01-18 16:46
Closing in-lieu of #5916

**Closed** 2021-01-18 16:47 UTC
Labels: sink: prometheus_exporter, type: bug
