### ISSUE TITLE
Lua transform changes empty array type to empty object

### ISSUE THREAD

**Issue by mikhno-s** [timberio/vector#2684] opened 2020-05-25 17:54 UTC
Hi again.

I found out that if I use lua transform my empty array in json output looks like `{}`, however it should be `[]` and it breaks my fathers processing.

For example I have `test.log` file:
```text
{"field": "test","empty_array": []}
{"field": "value", "array": [0.042]}
```

Also, I have next config:
```toml
data_dir = "${PWD}/data"

[sources.in]
    type = "file"
    include = ["test.log"]
    fingerprinting.fingerprint_bytes = 0
    fingerprinting.strategy = "checksum"
    fingerprinting.ignored_header_bytes = 0

[transforms.json]
    type = "json_parser"
    inputs = ["in"]
    drop_invalid = true

[transforms.transform]
    type = "lua"
    inputs = ["json"]
    
    version = "2"
    hooks.process = "process"
    source = """
      function process(event, emit)
        emit(event)
      end
    """
[sinks.my_sink_id]
  type = "console"
  inputs = ["transform"]
  target = "stdout"
  encoding.codec = "json"
```

the output will be:

```bash
$ vector --config test.tomlMay 25 20:49:53.079  INFO vector: Log level "info" is enabled.
May 25 20:49:53.081  INFO vector: Loading configs. path=["test.toml"]
May 25 20:49:53.094  INFO vector: Vector is starting. version="0.9.1" git_version="v0.9.1" released="Thu, 30 Apr 2020 15:34:34 +0000" arch="x86_64"
May 25 20:49:53.101  INFO vector::topology: Running healthchecks.
May 25 20:49:53.101  INFO vector::topology::builder: Healthcheck: Passed.
May 25 20:49:53.101  INFO vector::topology: Starting source "in"
May 25 20:49:53.103  INFO vector::topology: Starting transform "transform"
May 25 20:49:53.103  INFO source{name=in type=file}: vector::sources::file: Starting file server. include=["test.log"] exclude=[]
May 25 20:49:53.103  INFO vector::topology: Starting transform "json"
May 25 20:49:53.103  INFO vector::topology: Starting sink "my_sink_id"
May 25 20:49:53.105  INFO source{name=in type=file}:file_server: file_source::file_server: Found file to watch. path="test.log" file_position=0
{"empty_array":{},"field":"test","file":"test.log","host":"serhiimi-mac.local","source_type":"file","timestamp":"2020-05-25T17:49:53.110434Z"}
{"array":[0.042],"field":"value","file":"test.log","host":"serhiimi-mac.local","source_type":"file","timestamp":"2020-05-25T17:49:53.110994Z"}
```

Pay attention to `empty_array` field - it's empty object, not array.
Hence, was `[]` - becomes `{}` that is strange behaviour.

However, if I remove lua transform OR revert lua configuration to previous version (as was used before - w/o version, hooks.process and so on) - everything works as expected.

**Comment by mikhno-s** [comment] 2020-05-26 19:05
Ok, I see, that `{}` represents an empty array in lua. But in json an empty array is - `[]`

Hence - problem w/o encoding a lua empty array to json.

**Comment by binarylogic** [comment] 2020-08-07 16:20
Thanks @mikhno-s. I'm closing this since it appears there is not a bug here. Please reopen if I am not correct!

**Closed by binarylogic** 2020-08-07 16:20 UTC
Labels: transform: lua, type: bug
