### ISSUE TITLE
Investigate reported high CPU usage

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#4582] opened 2020-10-15 14:59 UTC
See https://discord.com/channels/742820443487993987/746070591097798688/766308591136931870

**Comment by spencergilbert** [comment] 2020-10-15 20:39
Not able to pin anything down :frowning: - look's like I'm consuming towards a whole core per Vector (daemonset) compared to 200m for the aggregators I'm running that are doing most of the transforms.

**Comment by binarylogic** [comment] 2020-10-15 21:07
cc @MOZGIII since this is related to k8s.

**Comment by MOZGIII** [comment] 2020-10-15 21:15
What message does the link point to? I can't tell which one discord opens. :(

**Comment by MOZGIII** [comment] 2020-10-15 21:18
> Not able to pin anything down 😦 - look's like I'm consuming towards a whole core per Vector (daemonset) compared to 200m for the aggregators I'm running that are doing most of the transforms.

Can you provide more data? Ideally the configuration, and the number of agents vs aggregators, and the average load per node.

**Comment by spencergilbert** [comment] 2020-10-16 14:33
@MOZGIII if you can excuse the "wrapping" this is the config for both charts: https://gitlab.com/-/snippets/2030000, ln15 in both is the start of the helm values.

**Comment by MOZGIII** [comment] 2020-10-16 22:34
Load on the nodes, yes. How many events per second, etc...

**Comment by spencergilbert** [comment] 2020-10-17 00:18
Moving back here from discord... Currently running @MOZGIII test image:

![image](https://user-images.githubusercontent.com/11903873/96323640-f8c01080-0feb-11eb-8159-372917a90cde.png)

Still seeing a _slow_ rise in memory usage. This still has `internal_metrics` routing into `blackhole`, but shouldn't matter based on the changes that were made in the test image.

This is a view of _high memory limits_ seeing a strong increase in memory usage on Oct 15 (using nightly), followed by some hilarity caused by reducing the limit drastically.

![image](https://user-images.githubusercontent.com/11903873/96323710-5c4a3e00-0fec-11eb-96cf-24719fe98e8b.png)

There doesn't appear to be a noticeable difference in used memory between `internal_metrics` -> `blackhole` vs into `prometheus`. I thought having large numbers of timeseries created from per filepath metrics might have caused the growth, but it seems like @MOZGIII 's test image has disproved that.

@Hoverbear linked https://github.com/timberio/vector/issues/2356 thinking it could be similar, but at this point I'm not sure.

**Comment by MOZGIII** [comment] 2020-10-17 15:28
My image completely disabled internal metrics, so if no difference is observed - the issue must be somewhere else. I created #4615 to expose the cardinality of the metrics directly as a counter, so this could be used to reassure the cardinality growth is manageable.

@spencergilbert so, it's only the agents that grow in size, right?

Could you post the effective configs here, so we have a better understanding what to expect? Also, some absolute value would be nice, as if the growth is in the order of kilobytes per minute it's expected, and if it's 10s of megabytes - it's probably something odd going on.



> @MOZGIII 's test image has disproved that.

For context, this is an image built from https://github.com/timberio/vector/pull/4606 and available at `mozgiii/vector-k8s-wip:bug1`.

**Comment by spencergilbert** [comment] 2020-10-17 18:54
Only the agents, yes. I suspect that `file` source metrics are the likely culprit...

Running config:
```toml
# Configuration for vector.
# Docs: https://vector.dev/docs/

# Data dir is location controlled at the `DaemonSet`.
data_dir = "/vector-data-dir"
[log_schema]
  host_key = "host"
  message_key = "message"
  source_type_key = "source_type"
  timestamp_key = "timestamp"
# Ingest logs from Kubernetes.
[sources.kubernetes_logs]
  type = "kubernetes_logs"
[sources.internal_metrics]
  type = "internal_metrics"
[sources.json_logs]
  type = "file"
  include = ["/var/log/kube-audit/*.json", "/var/lib/rancher/rke/log/*.log"]
  
[sources.system_logs]
  type = "file"
  include = ["/var/log/syslog*", "/var/log/auth.log*"]
  
[transforms.json_parser]
  type = "json_parser"
  inputs = ["json_logs"]
  drop_invalid = true
  
[sinks.kafka]
  type = "kafka"
  inputs = ["kubernetes_logs","json_parser","system_logs"]
  bootstrap_servers = "logging-kafka-bootstrap.logging-kafka:9092"
  topic = "test-vector"
  [sinks.kafka.buffer]
    max_size = 104900000
    type = "disk"
    when_full = "block"
  [sinks.kafka.encoding]
    codec = "json"
  
[sinks.prometheus]
  type = "prometheus"
  inputs = ["internal_metrics"]
  address = "0.0.0.0:9598"
  namespace = "vector"
```

The growth on the problematic ones are MiBs. Unfortunately I've lost the prometheus metrics I gathered overnight, so still working on getting nice graphs

**Comment by spencergilbert** [comment] 2020-10-17 19:15
![image](https://user-images.githubusercontent.com/11903873/96351717-4fc8f280-108b-11eb-8a78-17804dfb3dd5.png)

It seems most isolated to two nodes - I'm going to focus investigation there.

**Comment by spencergilbert** [comment] 2020-10-17 22:57
I'm starting to think it's not a regression, or related to metrics/cardinality - I've spend some time adjusting the config and the behavior appears related to the `json_logs` source I have. I guess there is something about the files being tailed that's making Vector unhappy. Something to do with the size, rotations, rate, etc of the files.

I've spent a lot of the day reading through other issues reported on the `file` source, the RFC, etc, but I'm still not sure how to properly debug/improve the setup.

That said - it doesn't seem like this issue is accurate at this point. I suspect we can close the issue and I can keep trying to improve performance of vector with those particular logs (and/or get help from y'all in another issue or over discord), ultimately up to you @MOZGIII @binarylogic

**Comment by MOZGIII** [comment] 2020-10-17 23:13
Seems like it's the kube-audit glob that's making the most trouble. What's that? https://github.com/Shopify/kubeaudit - this one?

**Comment by spencergilbert** [comment] 2020-10-17 23:40
Actually just the built-in kubernetes audit logs [here](https://kubernetes.io/docs/tasks/debug-application-cluster/audit/).

```
total 1.1G
-rw-r----- 1 root root 100M Oct 17 18:26 audit-log-2020-10-17T18-26-18.284.json
-rw-r----- 1 root root 100M Oct 17 18:56 audit-log-2020-10-17T18-56-52.798.json
-rw-r----- 1 root root 100M Oct 17 19:33 audit-log-2020-10-17T19-33-59.373.json
-rw-r----- 1 root root 100M Oct 17 20:10 audit-log-2020-10-17T20-10-42.278.json
-rw-r----- 1 root root 100M Oct 17 20:48 audit-log-2020-10-17T20-48-37.973.json
-rw-r----- 1 root root 100M Oct 17 21:24 audit-log-2020-10-17T21-24-45.539.json
-rw-r----- 1 root root 100M Oct 17 22:01 audit-log-2020-10-17T22-01-27.278.json
-rw-r----- 1 root root 100M Oct 17 22:38 audit-log-2020-10-17T22-38-57.899.json
-rw-r----- 1 root root 100M Oct 17 23:01 audit-log-2020-10-17T23-01-50.694.json
-rw-r----- 1 root root 100M Oct 17 23:22 audit-log-2020-10-17T23-22-43.427.json
-rw-r----- 1 root root  73M Oct 17 23:40 audit-log.json
```

**Comment by gustavoamigo** [comment] 2020-10-18 03:58
Guys, I am getting a very similar problem. 
<img width="440" alt="Screen Shot 2020-10-18 at 00 53 13" src="https://user-images.githubusercontent.com/4032109/96358322-516ed680-10dc-11eb-9fd0-86cfb90c39cb.png">

Here's my `vector.toml`
```
data_dir = "/var/lib/vector"

[sources.application]
include = ["/var/app/current/logs/application.log"]
type = "file"

[sources.infrastructure]
include = ["/var/log/awslogs.log", "/var/log/cfn-*.log",
    "/var/log/eb-*.log", "/var/app/current/logs/newrelic_agent.log", "/var/log/web*.error.log"]
type = "file"

[transforms.json-parsed-application]
type = "json_parser"
inputs = ["application"]
drop_field = true
drop_invalid = true

[transforms.rename-fields-application]
type = "rename_fields"
inputs = ["json-parsed-application"]
fields."@timestamp" = "timestamp"

[transforms.remove-fields-application]
type = "remove_fields"
inputs = ["rename-fields-application"]
fields = ["@version", "level_value","logger_name"]

[transforms.add-fields-all]
type = "add_fields"
inputs = ["remove-fields-application", "infrastructure"]
overwrite = true
fields.service_name = "$SERVICE"
fields.environment = "$ENVIRONMENT"
fields.git_hash = "$GIT_HASH"

[transforms.remove-fields-all]
type = "remove_fields"
inputs = ["add-fields-all"]
fields = ["source_type"]

[transforms.rename-fields-all]
type = "rename_fields"
inputs = ["remove-fields-all"]
fields."file" = "file_path"

[sinks.splunk]
type = "splunk_hec" # required
inputs = ["rename-fields-all"] # required
healthcheck = false
host = "https://$SPLUNK_HOST:$SPLUNK_PORT"
token = "$SPLUNK_TOKEN"
index = "$ENVIRONMENT"
encoding.codec = "json"
compression = "none"
buffer.type = "disk"
buffer.max_size = 104900000
```

```
$vector --version
vector 0.10.0 (g0f0311a x86_64-unknown-linux-gnu 2020-07-22)
```

A few things I've noticed:
* If I restart the service, it will start using the same amount of CPU as before.  
* If I change the buffering from `disk` to `memory`, the CPU usage goes down.

**Comment by binarylogic** [comment] 2020-10-18 04:24
Thanks, @gustavoamigo, we're actively investigating. Just to calrify, switching `buffer.type` to `"memory"` resolves the problem for you?

**Comment by spencergilbert** [comment] 2020-10-18 12:16
I'm not seeing ever increasing CPU usage, but that might be my rather aggressive cpu limits. I'll adjust those today and see if I can replicate

**Comment by gustavoamigo** [comment] 2020-10-18 15:20
@binarylogic yes, changing `buffer.type` to `"memory"` seems to solve the problem. I am going to switch all of our services to `memory` just to make sure. 

I will try the nightly release with our testing environment to see if there is any change.

**Comment by gustavoamigo** [comment] 2020-10-18 16:19
@binarylogic The problem happens with the nightly build as well. 
```
$vector --version
vector 0.11.0 (g1ec7a8b x86_64-unknown-linux-musl 2020-10-18)
```

<img width="891" alt="Screen Shot 2020-10-18 at 13 17 16" src="https://user-images.githubusercontent.com/4032109/96373639-46e82780-1144-11eb-8515-01c06e20d7cd.png">


Also, I had other problems with nightly build as well:
* vector-x86_64.rpm depends on the  GLIBC_2.18 version - it throws `'GLIBC_2.18' not found error`. I had to replace the binary with the one that comes from vector-x86_64-unknown-linux-musl.tar.gz file.
* The rename and remove transform won't work with my current `vector.toml` file. It won't work with fields that starts with `@`. They throw the following error. I use a logstash lib with my logback implementation in order to produce json logs, it produces fields names like `"@version"` and `"@timestamp"`
```
  |
1 | @timestamp
  | ^---
  |
  = expected lookup
```

```
  |
1 | @version
  | ^---
  |
  = expected lookup for key `transforms.remove-fields-application`
```

**Comment by jamtur01** [comment] 2020-10-18 16:32
@gustavoamigo What OS and version are you on?

I think the @-field thing is probably #4273.

**Comment by gustavoamigo** [comment] 2020-10-18 16:38
@jamtur01 It's the Amazon Linux version 1 (2018.03)

```
$ cat /etc/os-release
NAME="Amazon Linux AMI"
VERSION="2018.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2018.03"
PRETTY_NAME="Amazon Linux AMI 2018.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2018.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
```

```
$ cat /proc/version
Linux version 4.14.186-110.268.amzn1.x86_64 (mockbuild@koji-pdx-corp-builder-64003) (gcc version 7.2.1 20170915 (Red Hat 7.2.1-2) (GCC)) #1 SMP Tue Jul 14 02:57:34 UTC 2020
```

**Comment by spencergilbert** [comment] 2020-10-19 13:52
![image](https://user-images.githubusercontent.com/11903873/96459805-8a986b00-11f0-11eb-83d1-18f32098ff20.png)

These are metrics from the past 24h hours of my running vector limiting it to 1000mcpu and 1Gi of memory. Depending on the node they're running on, they've got drastically different usage profiles, not terribly surprising seeing how much certain things can be logging.

**Comment by MOZGIII** [comment] 2020-10-19 14:06
Great! Thanks for gathering and sharing this info!

From what I can tell, this looks good! The memory limit of 1Gi is reasonable and seems like 1000m works as well.

Last time I checked, in my local setup, `vector-agent` used 6 threads. We typically spawn a thread for the file IO per source (`file`/`kubernetes_logs` sources) and also keep a thread-pool for async IO. It would be reasonable to peek at how much threads your Vector uses on average, and set by CPU limit to `min(used_threads_count, you_cpu_cores_count/2)`, i.e. `6000m` for 6 threads on a 32 core system and `1000m` on a 2 core system. But this all really depends on the workload profile and particular use case.

I think we can close this issue.

Btw, I also see occasional CPU usage bursts, like at around 20:00. Didn't look into what causes those yet, and I guess those are fine too.

**Comment by MOZGIII** [comment] 2020-10-19 14:11
Actually, on the second thought - that blue line going up on the memory graph looks suspicious.

**Comment by spencergilbert** [comment] 2020-10-19 14:45
These machines are all 24core/48hyperthreads. Ideally we'd like to keep the footprint of the vector agent as small as possible, I figured most of the resource usage was going to come from the transformers and moved most of that to the aggregator, but that doesn't seem to be the case

**Comment by MOZGIII** [comment] 2020-10-19 18:57
So it kind of looks reasonable - the number of files to index grows consistently, and the memory consumption grows together with it.

**Comment by MOZGIII** [comment] 2020-12-04 20:18
The issue is gone somehow.

**Closed** 2020-12-04 20:18 UTC
Labels: domain: performance, type: task
