### ISSUE TITLE
Regex_parser not work well with multiple patterns

### ISSUE THREAD

**Issue by scarper123** [timberio/vector#3818] opened 2020-09-11 02:25 UTC
### Vector Version

```
vector 0.10.0 (g0f0311a x86_64-unknown-linux-gnu 2020-07-22)
```

### Vector Configuration File

```toml
[transforms.regex_parser_simple]
  inputs = []
  type = "regex_parser"
  patterns = [
  '^(?P<openstack_timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d+) (?P<openstack_pid>\d+) (?P<openstack_loglevel>[A-Z]+) (?P<openstack_program>\S+) \[(?P<openstack_reqlist>.*)\] (?P<openstack_client>\d{2,3}\.\d{2,3}.\d{1,3}.\d{1,3}) "(?P<http_request_method>[A-Z]+) (?P<http_request_path>\S+) (?P<http_request_version>\S+)" status: (?P<http_response_status>\d+) len: (?P<http_response_len>\d+) time: (?P<http_response_time>[\d\.]+)$',
  '^(?P<openstack_timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d+) (?P<openstack_pid>\d+) (?P<openstack_loglevel>[A-Z]+) (?P<openstack_program>\S+) \[(?P<openstack_reqlist>.*)\] (?P<openstack_client>\d{2,3}\.\d{2,3}.\d{1,3}.\d{1,3}) "(?P<http_request_method>[A-Z]+) (?P<http_request_path>\S+)" status: (?P<http_response_status>\d+) len: (?P<http_response_len>\d+) microversion: (?P<http_request_version>\S+) time: (?P<http_response_time>[\d\.]+)$',
]
[[tests]]
  name = "regex_parser_simple"
  [tests.input]
    insert_at = "regex_parser_simple"
    type = "raw"
    value = "2020-09-10 06:39:43.388 11728 INFO nova.osapi_compute.wsgi.server [-] 192.168.2.38 \"OPTIONS / HTTP/1.0\" status: 200 len: 501 time: 0.0004530"
  [[tests.outputs]]
    extract_from = "regex_parser_simple"
    [[tests.outputs.conditions]]
      "openstack_timestamp.equals" = "2020-09-10 06:39:43.388"
      "openstack_loglevel.equals" = "INFO"
      "http_request_version.equals" = "HTTP/1.0"
```

### Expected Behavior

The test result should be pass, because the raw data is matched with the first pattern

### Actual Behavior

Test failure, due "http_request_version.equals" = "HTTP/1.0"

### Example Data

```
2020-09-10 06:39:43.388 11728 INFO nova.osapi_compute.wsgi.server [-] 192.168.2.38 \"OPTIONS / HTTP/1.0\" status: 200 len: 501 time: 0.0004530
```

### Additional Context

When comment the second pattern, the test will pass. So it seems the multiple patterns are impact be other patterns.

### References
- [#1477](https://github.com/timberio/vector/issues/1477)

**Comment by bruceg** [comment] 2020-09-17 17:13
I cannot reproduce this with the current sources. I think this was fixed by #3096. Could you test with the current nightly download?

**Comment by scarper123** [comment] 2020-09-18 06:30
Can you tell me where to download the nightly version, I'm just download the release version "0.10.0".

**Comment by scarper123** [comment] 2020-09-18 06:37
Found the nightly version, and the test is passed.

I want to know when of you will release the latest stable version.


Thanks

**Comment by scarper123** [comment] 2020-09-21 06:37
I think this issue ticket can be close, thanks for help.

**Closed** 2020-09-21 06:37 UTC
Labels: meta: regression, transform: regex_parser, type: bug

**Comment by splitice** [comment] 2020-10-05 19:28
I've been running a random nightly since this fix. Seems solid. Given it's usefullness could this fix perhaps be backported to stable? Or is a stable release aproaching?
