### ISSUE TITLE
Get rid of flaky tests

### ISSUE THREAD

**Issue by lukesteensen** [timberio/vector#2978] opened 2020-07-08 21:27 UTC
We have a number of flaky tests that are imposing a heavy cost on our dev and CI process. We should have a strategy to eliminate them. I propose the following:

1. Identify the tests in question
2. For each test, open an issue describing its purpose and then delete the test entirely, linking the deletion commit in the issue
3. Triage the issues by cost/benefit to having the test based on the described purpose
4. Rewrite tests that are worthwhile

The tests currently provide negative value, so deleting them gets us back to a clean state as quickly as possible. We can then add them back (written in a more reliable fashion) as deemed valuable. If they're not valuable enough to rewrite, that's fine too.

**Comment by binarylogic** [comment] 2020-07-08 21:31
@lukesteensen @Hoverbear @fanatid @bruceg @ktff, could you list any tests that you are aware of and we can get to work on this? I'd like to compile a concrete list we can work against.

**Comment by Hoverbear** [comment] 2020-07-08 21:43
`encodes_histogram_without_timestamp`
[encodes_histogram_without_timestamp.log](https://github.com/timberio/vector/files/4893399/encodes_histogram_without_timestamp.log)

**Comment by ktff** [comment] 2020-07-10 11:09
`sources::journald::tests::filter_unit_works_correctly`
https://github.com/timberio/vector/runs/855687407

**Comment by ktff** [comment] 2020-07-10 11:12
@Hoverbear where did you see `encodes_histogram_without_timestamp` failing? It should only be failing in #2913 and it isn't merged.

**Comment by ktff** [comment] 2020-07-10 11:24
`topology::config::watcher::tests::multi_file_update` on mac
https://github.com/timberio/vector/pull/3010/checks?check_run_id=857600333

**Comment by Hoverbear** [comment] 2020-07-10 16:57
@ktff You're right! Sorry!

**Comment by Hoverbear** [comment] 2020-07-10 16:58
https://github.com/timberio/vector/issues/2978#issuecomment-656620358 is #3000

**Comment by ktff** [comment] 2020-07-11 21:10
`topology::reload_tests::topology_reuse_old_port` on windows
https://github.com/timberio/vector/pull/3010/checks?check_run_id=857742471

**Comment by ktff** [comment] 2020-07-11 21:32
https://github.com/timberio/vector/pull/3017#issuecomment-656849980

test_max_size_resume
[test_max_size_resume.log](https://github.com/timberio/vector/files/4905004/test_max_size_resume.log)

>I've seen this one before I think

@Hoverbear not suprising, they were addressed in #2862, but the race to the file mentioned in [comment](https://github.com/timberio/vector/pull/2862#discussion_r444125759) is quite persistent.

**Comment by ktff** [comment] 2020-07-11 22:07
`tests\tcp::merge` on windows
https://github.com/timberio/vector/pull/3010/checks?check_run_id=861595079

**Comment by ktff** [comment] 2020-07-11 22:11
`test_udp_syslog`
https://github.com/timberio/vector/pull/2955/checks?check_run_id=861560287

The PR changes `syslog` but not the `udp` part, and the test passes locally.

**Comment by ktff** [comment] 2020-07-19 11:23
`sinks::aws_s3::integration_tests::s3_waits_for_full_batch_or_timeout_before_sending`

https://github.com/timberio/vector/pull/3099/checks?check_run_id=886641917
https://github.com/timberio/vector/runs/868843252

**Comment by ktff** [comment] 2020-07-19 11:28
`sources::socket::test::tcp_gracefull_shutdown`

https://github.com/timberio/vector/runs/874679387

Seems to be failing because of OS errors, probably firewall.

**Comment by binarylogic** [comment] 2020-07-19 21:50
@ktff thanks for working through these. How are we feeling about closing this issue given the above? Are there tests left that we need to remove?

**Comment by ktff** [comment] 2020-07-19 22:15
>  Are there tests left that we need to remove?

Based on recent CI runs, these are the only flaky tests, so no.

It should be fine to close it. If another one popes up, it can be dealt with in a regular way.

**Comment by binarylogic** [comment] 2020-07-19 22:24
Sounds good 👍

**Comment by ktff** [comment] 2020-08-01 13:42
`merge_and_fork`

https://github.com/timberio/vector/runs/928235975

Either all messages pass, or none.

**Comment by ktff** [comment] 2020-08-13 15:11
As per https://github.com/timberio/vector/pull/3416#issuecomment-672414018

`test_reclaim_disk_space`

https://github.com/timberio/vector/runs/973409685

**Comment by JeanMertz** [comment] 2020-09-09 14:46
Re-opening, so that we can keep using this issue to track all flaky tests. We'll still create separate issues for each failing test, but link to this one so that you can easily cmd+F this issue to see if a test is already reported as being flaky (the GH search function doesn't always work as well as you want it to, unfortunately).

**Comment by binarylogic** [comment] 2020-10-11 17:01
Closing this since the issue is not particularly helpful anymore. Please continue to open individual issues for each test removed.

**Closed by binarylogic** 2020-10-11 17:01 UTC
Labels: domain: tests, type: bug, type: tech debt
