### ISSUE TITLE
Can the file sink support reopen?

### ISSUE THREAD

**Issue by panpan-wu** [timberio/vector#2774] opened 2020-06-10 06:47 UTC
I want to use logrotate to rotate files created by the file sink. After rotate, I'd like the file sink can reopen file, how to do it?

Or can the file sink support max file size and max file number option? What I want to do is to limit the size and number of the file.

**Comment by binarylogic** [comment] 2020-07-28 21:58
Thanks @panpan-wu, and sorry for the delay. Vector should reopen the file if it is no longer present. We'll get this fixed and add a test.

**Comment by juchiast** [comment] 2020-07-29 02:50
I'm able to reproduce the bug, working on fixing it.

**Comment by juchiast** [comment] 2020-07-29 09:13
@panpan-wu you can use `copytruncate` option to prevent the file from being unlinked (docs in https://linux.die.net/man/8/logrotate).

@binarylogic this looks like a duplication of #2055, I think if `copytruncate` works we can close this issue and continue the discussion there.

**Comment by binarylogic** [comment] 2020-07-29 14:51
You're correct. Let's close. I would like to update our docs to mention this #3249.

**Closed by binarylogic** 2020-07-29 14:51 UTC
Labels: have: should, sink: file, type: bug, type: enhancement, type: help
