### ISSUE TITLE
How to debug prometheus source

### ISSUE THREAD

**Issue by KannarFr** [timberio/vector#2668] opened 2020-05-22 13:05 UTC
```
~ # RUST_LOG=debug vector 
May 22 13:02:16.920  INFO vector: Log level "info" is enabled.
May 22 13:02:16.920  INFO vector: Loading configs. path=["/etc/vector/vector.toml"]
May 22 13:02:16.923  INFO vector: Vector is starting. version="0.9.1" git_version="v0.9.1" released="Thu, 30 Apr 2020 08:24:03 +0000" arch="x86_64"
May 22 13:02:16.923  INFO vector::topology: Running healthchecks.
May 22 13:02:16.923  INFO vector::topology: Starting source "prometheus"
May 22 13:02:16.923  INFO vector::topology::builder: Healthcheck: Passed.
May 22 13:02:16.923  INFO vector::topology: Starting sink "stdout"
May 22 13:02:16.937 ERROR source{name=prometheus type=prometheus}: vector::internal_events::prometheus: parsing error error=Malformed
^CMay 22 13:02:18.401  INFO vector: Shutting down.
```

There are tools/commands to print what is malformed to debug this?

**Comment by KannarFr** [comment] 2020-05-22 13:08
LOG env var, nvm.

**Comment by KannarFr** [comment] 2020-05-22 13:08
LOG env var to debug doesn't print the malformed body.

**Comment by KannarFr** [comment] 2020-05-22 13:15
Does the request follows redirections?

**Comment by Hoverbear** [comment] 2020-05-22 16:10
@KannarFr You can try `vector -vvv` to enable trace logging. :)

Reviewing the code, this is possibly caused by the following:

* The response from Prometheus was not in UTF-8.
* The host may not be sending plaintext metrics. (is it compressed? some different format?)

A metric should look like one of the ones found around here:

https://github.com/timberio/vector/blob/17340e26b0845ed95519027950a0bd9d388df71d/src/sources/prometheus/parser.rs#L510-L513

Regarding redirects, we do a [`hyper::Request::get`](https://docs.rs/http/0.2.1/http/request/struct.Builder.html) which as far as I can tell does not automatically follow redirects. This might be worth adding handling for on our side!

**Comment by Hoverbear** [comment] 2020-05-22 16:14
We might also be able to improve this message:

https://github.com/timberio/vector/blob/17340e26b0845ed95519027950a0bd9d388df71d/src/sources/prometheus/parser.rs#L488-L490

**Comment by binarylogic** [comment] 2020-08-07 17:45
@juchiast assigning this to you since it is related to https://github.com/timberio/vector/pull/3286.

**Closed** 2020-08-19 04:21 UTC
Labels: domain: observability, have: should, source: prometheus, type: bug
