### ISSUE TITLE
[VRL] unhandled error in string concatenation of non-literal `null`s

### ISSUE THREAD

**Issue by hhromic** [timberio/vector#7214] opened 2021-04-22 09:43 UTC
### Vector Version

```
vector 0.13.0 (v0.13.0 x86_64-unknown-linux-gnu 2021-04-21)
```

### Actual Behavior

Consider the following string concatenation operations and their actual results:
```
$ "hello" + " " + "vector"
"hello vector"

$ "hello" + " " + null
"hello "

$ null + " " + "vector"
" vector"

$ arr[10]
null

$ "hello" + " " + arr[10]

error[E100]: unhandled error
  ┌─ :1:1
  │
1 │ "hello" + " " + arr[10]
  │ ^^^^^^^^^^^^^^^^^^^^^^^
  │ │
  │ expression can result in runtime error
  │ handle the error case to ensure runtime success
  │
  = see documentation about error handling at https://errors.vrl.dev/#handling
  = learn more about error code 100 at https://errors.vrl.dev/100
  = see language documentation at https://vrl.dev
```

### Expected Behavior

Instead, I was expecting the actual result of the last expression to be:
```
$ "hello" + " " + arr[10]
"hello "
```

### Additional Context

DIscovered this behaviour while trying to do the following in VRL:
```
fields = parse_csv!(del(.message))
.eventTime = to_int(parse_timestamp!(fields[1] + " " + fields[2], format: "%D %T")) * 1000
```

To workaround the problem I simply coalesce the expression error like this:
```
.eventTime = to_int(parse_timestamp!(fields[1] + " " + fields[2] ?? null, format: "%D %T")) * 1000
```

Perhaps I'm missing something here and therefore should be added to the documentation?
Thanks!

**Comment by JeanMertz** [comment] 2021-06-29 08:06
I don't actually believe this is a bug.

In your examples, all input _except_ `arr[10]` is known at compile-time.

It's because the type of `arr[10]` is unknown that that specific example fails.

See:

```coffee
$ arr[10] = null
null

$ "hello" + " " + arr[10]
"hello "
```

It works in this case because I explicitly set `arr[10]` to `null`, but if I try any other value, it'll fail because it can't know at compile-time whether a specific index in an array is set and which type of value is set within that index, when that array originates from an event:

```coffee
$ "hello" + " " + arr[9]

error[E100]: unhandled error
  ┌─ :1:1
  │
1 │ "hello" + " " + arr[9]
  │ ^^^^^^^^^^^^^^^^^^^^^^
  │ │
  │ expression can result in runtime error
  │ handle the error case to ensure runtime success
  │
  = see documentation about error handling at https://errors.vrl.dev/#handling
  = learn more about error code 100 at https://errors.vrl.dev/100
  = see language documentation at https://vrl.dev
```

The error itself could be improved to make this more clear. cc #7204

**Comment by hhromic** [comment] 2021-06-29 09:35
@JeanMertz interesting. So it seems that what got confused is that Vector doesn't distinguish between undefined and an actual `null` value?

```rust
$ arr[8] = "there"
$ arr[10] = null
$ "hello" + " " + arr[8]   # value is the string "there" (it works)
$ "hello" + " " + arr[9]   # value is undefined (it doesn't work)
$ "hello" + " " + arr[10]  # value is `null` (it works)
```

However, if you visualise the `arr` array:
```rust
$ arr
[null, null, null, null, null, null, null, null, "there", null, null]
```

Which ones are `null` and which ones are undefined?

I initially thought that undefined values are coalesced to `null` values during expression evaluation, hence why I considered this behaviour a bug.

So I guess the questions here are:
* should VRL distinguish undefined from `null` ?
* should the printing of undefined values be more clear and distinguishable from `null`?
* should Vector actually coalesce undefined values to `null`s in expression evaluation?

I think the third point would be very useful for writing concise  VRL programs without so much error handling boiler plate.

**Comment by JeanMertz** [comment] 2021-06-29 12:44
> So it seems that what got confused is that Vector doesn't distinguish between undefined and an actual `null` value?

That's correct. We did discuss this at some point, but opted not to go that route (yet).

However, we do have a function that allows you to distinguish between non-existing fields/indices, and `null` values:

```coffee
$ foo[0] = null
null

$ exists(foo[0])
true

$ exists(foo[1])
false
```

**Comment by JeanMertz** [comment] 2021-06-29 12:51
>     * should Vector actually coalesce undefined values to `null`s in expression evaluation?
> 
> 
> I think the third point would be very useful for writing concise VRL programs without so much error handling boiler plate.

I don't think this is a direction we want to go in. True, it would reduce the amount of error handling, but it wouldn't reduce the amount of _potential runtime bugs_.

Note that we're not necessarily talking about _undefined_ values, but _unknown_ values. Events come in at runtime, and we can't know (not yet at least, at some point we'll support compile-time event schema's) the type of each field without you informing the compiler about the types in your code.

So, your solution would be saying we'd treat every event field as `null`, and allow any null-operations on unknown fields. That's dangerous, because we'd allow you to write:

```coffee
$ foo = "hello: " + .username
```

But for all we know, `.username` could be an array, or an object, or any other type for which it doesn't make sense to concatenate it to a string. By requiring you to handle this situation, you can be sure that you don't run into any surprises at runtime, at the expense of (as you mentioned) having to write more error handling logic.

This was a conscious decision and a cornerstone of the language. We did add the "abort function call" error-handling logic (e.g. `my_function!` the bang at the end) to make it easier to handle errors that you _know_ can't happen, but we still want to make those cases clear in the source code, instead of hiding it internally by treating unknown values as null values.

**Comment by hhromic** [comment] 2021-06-29 13:51
> However, we do have a function that allows you to distinguish between non-existing fields/indices, and `null` values:

Ah yes, we are aware of these functions indeed. But we were aiming on reducing the amount of boilerplate.

> I don't think this is a direction we want to go in. True, it would reduce the amount of error handling, but it wouldn't reduce the amount of _potential runtime bugs_.

Yes I understand and I agree with you.

> But for all we know, `.username` could be an array, or an object, or any other type for which it doesn't make sense to concatenate it to a string. By requiring you to handle this situation, you can be sure that you don't run into any surprises at runtime, at the expense of (as you mentioned) having to write more error handling logic.
>
> This was a conscious decision and a cornerstone of the language. We did add the "abort function call" error-handling logic (e.g. `my_function!` the bang at the end) to make it easier to handle errors that you _know_ can't happen, but we still want to make those cases clear in the source code, instead of hiding it internally by treating unknown values as null values.

Indeed, static typing is a desired feature and we do value it very much in Vector.
I guess then that the way to go is to just add more explicit error handling and accept that it is a trade-off for achieving compile-time correctness.

Thanks for the explanation and interesting discussion. I do agree now that in these terms indeed this is not a bug.

However, improving the way "undefined" and `null` is visualised in all object printing would definitively be an improvement then. At least we would understand much easier what is wrong when developing pipelines.

Due to the above, I'm not sure if I should close this issue, leave it open, or file a new one. Let me know!

**Comment by JeanMertz** [comment] 2021-06-29 14:11
> However, improving the way "undefined" and `null` is visualised in all object printing would definitively be an improvement then. At least we would understand much easier what is wrong when developing pipelines.

Yeah, I agree with this. The problem is that whatever we print as output is expected to be valid VRL syntax.

So, your example of:

```coffee
$ arr
[null, null, null, null, null, null, null, null, "there", null, null]
```

can't currently be represented in any other way, unless we add a new primitive type that explicitly represents "unknown". That would definitely be a breaking change, but I do agree that the current situation can be confusing during debugging.

Let's leave this issue open for now, maybe @jszwedko has some thoughts on this as well.

**Comment by jszwedko** [comment] 2021-06-29 18:38
Ah yes, I see, thanks for the discussion both!

I agree that further distinguishing between `null` and `undefined` would help here such that:

```
$ arr[10]
null
```

Would print `undefined` rather than `null`.

In the specific case of:

```
error[E100]: unhandled error
  ┌─ :1:1
  │
1 │ "hello" + " " + arr[10]
  │ ^^^^^^^^^^^^^^^^^^^^^^^
  │ │
  │ expression can result in runtime error
  │ handle the error case to ensure runtime success
  │
  = see documentation about error handling at https://errors.vrl.dev/#handling
  = learn more about error code 100 at https://errors.vrl.dev/100
  = see language documentation at https://vrl.dev
```

It seems like at that point the compiler should know that `arr[10]` is undefined rather than "unknown" (such that the error condition needs to be handled).

I'll close this, but link it to #7204 and #7203 so that it can be used as an example when considering improvements that can be mode here.

Thanks again for reporting this @hhromic !

**Closed** 2021-06-29 18:38 UTC
Labels: domain: vrl, type: bug
