### ISSUE TITLE
Support global proxies that can intercept outbound requests

### ISSUE THREAD

**Issue by LucioFranco** [timberio/vector#1770] opened 2020-02-10 23:27 UTC
As a user I'd like to setup proxies that vector can use to send events through. The major use case I see here is https://github.com/grafana/loki/blob/master/docs/operations/multi-tenancy.md and https://github.com/grafana/loki/blob/master/docs/clients/promtail/configuration.md#client_config.

I am not exactly sure what the right steps are to achieve this feature but looking at how other rust crates seem to handle proxies we could let users provide a list of proxies and possible filters for hosts that would be sent via that proxy. These options could be global to the whole instance of vector and our sinks would be aware and would know how to send logs via these proxies.

**Comment by chouclee** [comment] 2020-09-20 07:21
Provide another use case here, as an Enterprise user, the outbound traffic is typically controlled via firewall rules or has to go through proxies setup by network teams. If vector is used to collect data within the company network, and the sink  (e.g. s3, gcs) destinations are 3rd party providers, this would be a nice (probably required)  feature for this use case.

**Comment by binarylogic** [comment] 2020-11-11 18:29
Escalating this to `must` since we are hearing this as a blocker for some users.

Ideally, this would be controlled through config-level settings as well as environment variables.

**Comment by fuchsde** [comment] 2021-07-06 11:09
The feature would be awesome for me as well! +1

**Comment by jszwedko** [comment] 2021-07-26 19:16
I think this is a duplicate of #6401 which is being worked on now in #8205

**Closed by jszwedko** 2021-07-26 19:16 UTC
Labels: domain: networking, domain: reliability, have: must, needs: more demand, needs: requirements, sink: loki, type: feature
