### ISSUE TITLE
Tests involving disk buffers fail on NixOS

### ISSUE THREAD

**Issue by a-rodin** [timberio/vector#1503] opened 2020-01-09 20:55 UTC
Here is an example: https://app.circleci.com/jobs/github/timberio/vector/70981.

It might be related to some recent changes in the buffers, as these tests worked in https://github.com/timberio/vector/pull/1432 on two weeks old `master` branch.

**Comment by binarylogic** [comment] 2020-01-09 23:43
@LucioFranco do you mind seeing what's going on here (assuming it's related to recent work?)

**Comment by LucioFranco** [comment] 2020-01-09 23:45
@a-rodin do you know how I can reproduce this locally? Seems like just a slow system, that assert I believe relates to total events passed through so unless there was an error I doubt its the disk buffer.

**Comment by binarylogic** [comment] 2020-01-09 23:54
@LucioFranco can you try running the tests on the `nix` docker image? And even if the test is slow, is there a way to deterministically wait for the test to complete?

**Comment by LucioFranco** [comment] 2020-01-09 23:56
@binarylogic yeah I can, will do so tomorrow.

**Comment by a-rodin** [comment] 2020-01-10 12:48
It is possible to run these tests locally in Docker using this command:

```bash
./scripts/docker-run.sh verifier-nixos ./scripts/verify-nix.sh
```

**Comment by LucioFranco** [comment] 2020-01-10 19:47
I am having issues with running that command:

```
[BUG] Bus Error at 0x00007f502bd0ca2c
ruby 2.6.4p104 (2019-08-28) [x86_64-linux]

-- Machine register context ------------------------------------------------
 RIP: 0x00007f502bd0ca2c RBP: 0x00007ffdf5653fd0 RSP: 0x00007ffdf5653ed8
 RAX: 0x00007f502bd0ca2c RBX: 0x00007f502bde4000 RCX: 0x0000000000000000
 RDX: 0x0000000000000000 RDI: 0x00007f502bde3010 RSI: 0x0000000000000001
  R8: 0x0000000000000000  R9: 0x00007f502bc4b7c8 R10: 0x00007f502bde3000
 R11: 0x0000000000000206 R12: 0x00007f502bde2c40 R13: 0x00007ffdf5653f28
 R14: 0x00007f502c1fa008 R15: 0x00000000ffffffff EFL: 0x0000000000010202

-- C level backtrace information -------------------------------------------
Bus error
```

this is on WSL2 with docker desktop edge with WSL2 support.

**Comment by LucioFranco** [comment] 2020-01-13 22:49
Update: Both @a-rodin and I finally got this running locally. We both had it passing which tells me the CI machines are just being too slow. The test is correct and everything passes on a larger machine.

**Comment by LucioFranco** [comment] 2020-01-13 22:49
Going to close this issue since technically the test passes and the larger time we applied has seemed to fix it.

**Closed by LucioFranco** 2020-01-13 22:49 UTC
Labels: domain: buffers, domain: testing, type: bug
