### ISSUE TITLE
Possible BytesMut usage instead Bytes in Event

### ISSUE THREAD

**Issue by fanatid** [timberio/vector#3473] opened 2020-08-16 09:43 UTC
In PR #3460 I removed bytes:0.4 (updated to bytes:0.5). As a result in a function `merge_value` we need to create BytesMut from two Bytes objects. For better performance, we would able to use BytesMut in Event instead of Bytes. We should check is it possible or not.
https://github.com/timberio/vector/blob/8e7a3674ffca11b13a3a87dcf69d7254f2083e98/src/event/merge.rs#L24-L34

**Comment by MOZGIII** [comment] 2020-08-17 14:48
I totally agree. I was working on `LineAgg`, and it's apparent this is very necessary to implement the operations efficiently - not only from the performance point of view, but also in the sense of how much code complexity we have.

**Comment by bruceg** [comment] 2020-08-17 17:09
How often is `merge_value` done? Will this increase the cost of cloning an `Event`? Which factor is more relevant here?

**Comment by lukesteensen** [comment] 2020-08-19 22:12
For many of our sources, storing a `BytesMut` would require an additional copy at event creation time. The current implementation essentially defers that copy until the value actually needs to be mutated, which seems like a good tradeoff to me. Mutating values in place is not as common as event creation, cloning for fanout, etc.

**Comment by MOZGIII** [comment] 2020-08-24 07:03
If that's the case, the `Bytes` values we're using at the events must be original read buffers to where the data was read (i.e. when the reader decides on what kind of buffer it wants to offer). It looks like a quite poor abstraction on the readers' side. If we could fix that, it seems like we could implement it eliminating the extra copies.
One thing to note is `bytes` `0.4` had somewhat different semantics in the API compared to `bytes` `0.5`, but we didn't properly revisit our architectural decisions while transitioning. It might help if we do so.

Also, I can agree that mutating value in place is not as common, but without the ability to do so we need to keep the support structures around to perform those mutations if we even need to. The mutation process would then consist of taking an event, removing the read-only `Bytes` field from it, converting it into `BytesMut`. Then the mutations can be performed to the `BytesMut` living separately from the `Event` without the field until the `Event` can be released - this is done by freezing `BytesMut` back to `Bytes` and re-adding it into the `Event` - and then releasing the reconstructed event. This is a crazy amount of work and complexity, but I don't see an easier way to achieve it. Btw, if you have a better idea - please let me know, I could use it for my `LineAgg` integration work.

**Comment by lukesteensen** [comment] 2020-08-24 18:27
> If that's the case, the `Bytes` values we're using at the events must be original read buffers to where the data was read (i.e. when the reader decides on what kind of buffer it wants to offer). It looks like a quite poor abstraction on the readers' side. If we could fix that, it seems like we could implement it eliminating the extra copies.

I'm not really following your logic here. You can read more about the design in [the docs](https://docs.rs/bytes/0.5.6/bytes/), but yes the idea is to read once from the networks and then split into frames, parse, pass around, etc without additional copies. I do not think that is a bad abstraction, but a rather helpful one that lets us avoid copies on virtually every event.

I don't want to spend too much time on this, but I also question whether you could achieve this optimization while still allowing mutation. Right now, the `Bytes` value in events is often a reference into a large contiguous buffer of consecutive network reads. You could theoretically allow in-place mutation iff you could prove exclusive access to the specific subslice, but even that would not help here. To allow appending additional data, you'd need there be no active data immediately following your current subslice, which means you'd need your own buffer instead of a shared one, which defeats the purpose. Maybe with length-delimited protocols you could provide correctly-sized buffers ahead of time, but the majority of our input data is newline-delimited where you can't know that ahead of time and would be forced to do copies.

> The mutation process would then consist of taking an event, removing the read-only `Bytes` field from it, converting it into `BytesMut`. Then the mutations can be performed to the `BytesMut` living separately from the `Event` without the field until the `Event` can be released - this is done by freezing `BytesMut` back to `Bytes` and re-adding it into the `Event` - and then releasing the reconstructed event. This is a crazy amount of work and complexity, but I don't see an easier way to achieve it.

Isn't the alternative the code @fanatid posted in the original issue? That does not seem like a crazy amount of work or complexity to me. I understand that it is not an optimal number of memory copies, but memory copies are generally very fast and we should verify that they are a bottleneck here before making our implementation more complex or forcing there to be more copies everywhere else. And even with a simple `Vec`, you'd likely get a number of full copies as it needed to resize to fit the growing data.

Another alternative would be to collect the `Byte` values into an `Array` value on the event, and then keep track of which need to be joined when the event is emitted. In theory that would be even more efficient than a `Vec`-backed `BytesMut`, since you'd be able to avoid all of the intermediate copies and go directly into a buffer of the final size.

**Comment by MOZGIII** [comment] 2020-08-24 22:38
> Isn't the alternative the code @fanatid posted in the original issue?

No, this is different. The problem comes from the need to operate on the `Event` rather than the raw `Bytes` or `Value`. Also, the example above only performs merge once, while in the line aggregation case we'd want to convert `Bytes` => `BytesMut`, then merge a number of following `Bytes` into that `BytesMut`, and then, finally, only freeze `BytesMut` => `Bytes` once.

Wouldn't something similar to `Cow` be a perfect fit for us here? Then we wouldn't have to choose whether to pass around read-only slices or read-write copied of the original data - we'll be able to work with both transparently. We can't use `std::borrow::Cow` with `bytes`, but how about `enum Cow { Bytes(Bytes), BytesMut(BytesMut) }`? If we use this representation in the `Value` - it'd be possible to effectively reduce the amount of copies among both cases: when we just pass the values along, and when we need to mutate them somehow.


> Another alternative would be to collect the `Byte` values into an `Array` value on the event, and then keep track of which need to be joined when the event is emitted. In theory that would be even more efficient than a `Vec`-backed `BytesMut`, since you'd be able to avoid all of the intermediate copies and go directly into a buffer of the final size.

I like this idea, it fits the LineAgg needs well. I'll play with it and see if the logic can be fully implemented through that, thx for pointing this out.

**Comment by lukesteensen** [comment] 2020-08-25 02:02
> No, this is different. The problem comes from the need to operate on the `Event` rather than the raw `Bytes` or `Value`.

I'm not following. It seems to me that the code above is currently being used as part of an `Event`-level merge and works just fine. The issue is whether we should try to optimize it to do fewer copies.

`LineAgg` intentionally happens before data is turned into an `Event`, so it shouldn't matter how we represent data within `Event`. And it seems like `LineAgg` is already using a `BytesMut` for its intermediate state, so I'm not sure what we're discussing.

**Comment by MOZGIII** [comment] 2020-08-25 14:18
> `LineAgg` intentionally happens before data is turned into an `Event`, so it shouldn't matter how we represent data within `Event`.

`LineAgg` needs to preserve the data from the first event that contributed to the aggregated event. It's interface has so far been implemented around receiving a `line` and a `filename` that that line comes from. The `filename` being both the key the event merges on and the data to carry-on to the emitted events. In some cases we emit two lines - and the first of those line is the aggregated one. If we don't have context for it, we can't inflate it to an event. We can in case of `file` source, but that's not enough for `docker` source.

**Comment by binarylogic** [comment] 2020-08-31 00:33
What's the status here? Should we close this or keep it open?

**Comment by MOZGIII** [comment] 2020-08-31 11:42
Let's close it for now. We can reopen when we have a more concrete proposal.

**Closed by MOZGIII** 2020-08-31 11:42 UTC
Labels: domain: data model, domain: performance, type: tech debt
