### ISSUE TITLE
Vector Sink docs shouldn't specify an encoding section 

### ISSUE THREAD

**Issue by StephenWakely** [timberio/vector#8589] opened 2021-08-04 10:46 UTC
The [docs](https://vector.dev/docs/reference/configuration/sinks/vector/#encoding) for the Vector sink specifies an encoding section that doesn't exist.

Trying to run with encoding specified produces the following error:

```
Aug 04 11:44:46.454 ERROR vector::cli: Configuration error. error=data did not match any variant of untagged enum VectorConfig for key `sinks.vectorout` at line 4 column 1
```

**Comment by spencergilbert** [comment] 2021-08-04 12:20
I believe this is a duplicate of https://github.com/timberio/vector/issues/8138

**Closed by spencergilbert** 2021-08-04 12:20 UTC
Labels: domain: external docs, type: bug
