### ISSUE TITLE
Fluent Bit & Correctness

### ISSUE THREAD

**Issue by edsiper** [timberio/vector#727] opened 2019-08-08 16:22 UTC
Hi Folks, 

thanks for reaching out. Regarding the information posted about Fluent Bit and it features, a couple of items needs to adjust:

## Disk buffer persistency

This mechanism is implemented and documented in our [Buffer/Storage](https://docs.fluentbit.io/manual/configuration/buffering) section.

Note that your performance test enable storage filesystem type here:

https://github.com/timberio/vector-test-harness/blob/master/cases/disk_buffer_performance/ansible/config_files/td-agent-bit.conf#L16

## File Rotate Copytruncate

I think this test is not somewhat adecuated. Looking at the logrotate documentation a copytruncate mode is prone to data loss, note that this mechanism exists for applications that usually don't close the file descriptor where they are writing data to:

```
       copytruncate
              Truncate the original log file to zero size in place after  cre‐
              ating  a copy, instead of moving the old log file and optionally
              creating a new one.  It can be used when some program cannot  be
              told  to  close its logfile and thus might continue writing (ap‐
              pending) to the previous log file forever.  Note that there is a
              very  small  time  slice between copying the file and truncating
              it, so some logging data might be lost.   When  this  option  is
              used, the create option will have no effect, as the old log file
              stays in place.
```

the workflow is the following at rotation time:

- copy actual file buffer data to a new file
- truncate actual file

if we look at the test, here is checking for a pending ```write``` that should not be monitored. 

```
    - name: Rotate file with new data
      shell: |
        cp {{ test_file_location }} {{ test_file_location }}0
        truncate -s 0 {{ test_file_location }}
        echo "New file line" > {{ test_file_location }}
        sleep 5
        echo "Last line" >> {{ test_file_location }}0
```

Since data loss can be expected, this mechanism, in general, can be discouraged. Here is also some insights from Splunk behavior:

https://answers.splunk.com/answers/185453/why-copytruncate-logrotate-does-not-play-well-with.html

Note that if logrotate enable compression in the newly copied file, likely you will get garbage. My point is: monitoring a newly created file due to copytruncate mode adds unnecessary overhead where data loss or garbage could be expected.

## JSON Wrapper

Would you please test using latest Fluent Bit version ?, I suspect an older version was tested, we had some issues in the past.

## Final comments

I am interested in following the conversation, comments are welcome.

**Comment by binarylogic** [comment] 2019-08-10 15:25
Thanks @edsiper, and it was great talking this week. We're planning to do some work on our test hardness in the next week or 2 and will align some of these changes as part of that work.

**Comment by binarylogic** [comment] 2019-12-03 05:25
@edsiper sorry for the delay on this. I'm responding for posterity.

### Disk buffer persistency

> This mechanism is implemented and documented in our Buffer/Storage section.

Fluentbit fails this test, it was not a problem of misconfiguration (to the best of my knowledge). You can see that we enabled disk persistence here:

https://github.com/timberio/vector-test-harness/blob/master/cases/disk_buffer_persistence_correctness/ansible/config_files/td-agent-bit.conf#L12

### File Rotate Copytruncate

> I think this test is not somewhat adecuated. Looking at the logrotate documentation a copytruncate mode is prone to data loss

Right, but the test is not. It's just testing that checkpoints are followed properly when data is copied, which for Fluentbit it is not. If you look at the test, we [aren't actually executing a `copytruncate` command](https://github.com/timberio/vector-test-harness/blob/master/cases/file_rotate_truncate_correctness/ansible/run.yml#L38-L44), just mimicking its behavior in a controlled fashion, one that doesn't encounter the edge case you're referring to.

> Since data loss can be expected, this mechanism, in general, can be discouraged.

Sure, we're not advocating this method, just verifying correct behavior. Just because the method is not ideal doesn't mean that support should be ignored. There are plenty of scenarios where a user doesn't have a choice and needs a log forwarder that performs correctly for this method.

### JSON Wrapper

> Would you please test using latest Fluent Bit version ?, I suspect an older version was tested, we had some issues in the past.

We tested on the latest version at the time. I noticed that the day after we exposed these issues a number of JSON related commits were made and then a release was made:

1. https://github.com/fluent/fluent-bit/commit/8492d8c0dba0c5d36d2c9c687dfb296e762bc685
2. https://github.com/fluent/fluent-bit/commit/6fa1d640b6ee33969ad89e6570834be5961d037f
3. https://github.com/fluent/fluent-bit/commit/bd3e012acc0c50a4e1deda86f28a33069171a4b7
4. https://github.com/fluent/fluent-bit/commit/621e55b13e815b68cf0a6ca1aa67df80cf2bd11e
5. https://github.com/fluent/fluent-bit/commit/09c669c4998c1bf73b8a54b9060c32d63847e368
6. https://github.com/fluent/fluent-bit/commit/9b00fadf7d874eafda78ee657f26ec35423390f7
7. https://github.com/fluent/fluent-bit/commit/efdcc2a1373608919edaaa938abff8c7a1148fea

These commits appeared to resolve https://github.com/fluent/fluent-bit/issues/1278 which referenced _13 other JSON issues_. Some of which were open for almost a year, but resolved in a day. 😄 

---

Let me know if I can clarify any of this. We plan to expand our test suite but will not be including other subjects since the initial purpose was to establish a baseline for launching Vector. I'd definitely encourage that you perform similar integration tests on Fluentbit before releasing it.

**Closed** 2019-12-03 05:25 UTC
Labels: domain: testing, type: task

**Comment by l2dy** [comment] 2020-11-16 08:11
@binarylogic Could you please re-test "JSON (wrapped)" with the latest version of Fluent Bit? It's a bit unfair to have an X in timberio/vector's README, if the issue has been fixed in Fluent Bit.

**Comment by binarylogic** [comment] 2020-11-16 15:10
@l2dy sure. We are planning to re-run our test harness tests with our next release since it includes a number of performance enhancements. I'm curious, how did you find this issue?

PS - fluentbit still suffers from JSON parsing issues.

**Comment by l2dy** [comment] 2020-11-17 02:11
> @l2dy sure. We are planning to re-run our test harness tests with our next release since it includes a number of performance enhancements. I'm curious, how did you find this issue?

I've been watching this issue since @edsiper mentioned it in https://github.com/fluent/fluent-bit/issues/1580.

> PS - fluentbit still suffers from JSON parsing issues.

Thanks. I'll look into this.

**Comment by l2dy** [comment] 2020-11-17 02:33
Is the `wrapped_json_correctness` [configuration](https://github.com/timberio/vector-test-harness/blob/ead8a2fc3544a110d72b467c5c544edbfe330c7e/cases/wrapped_json_correctness/ansible/config_files/td-agent-bit.conf) missing `Parsers_File` (which is used in `regex_parsing_performance` [config](https://github.com/timberio/vector-test-harness/blob/ead8a2fc3544a110d72b467c5c544edbfe330c7e/cases/regex_parsing_performance/ansible/config_files/td-agent-bit.conf))? Can you help check the output (stdout & stderr) of Fluent Bit in `wrapped_json_correctness`? @binarylogic 

And also, `Path` in the file output config is a directory path in recent versions, see https://docs.fluentbit.io/manual/pipeline/outputs/file.

Fixing all that, running the test command on my machine seems to work.

**Comment by binarylogic** [comment] 2020-12-02 05:30
> Is the wrapped_json_correctness configuration missing Parsers_File

No, we have it defined [here](https://github.com/timberio/vector-test-harness/blob/ead8a2fc3544a110d72b467c5c544edbfe330c7e/cases/wrapped_json_correctness/ansible/config_files/td-agent-bit.parsers.conf)

> Fixing all that, running the test command on my machine seems to work.

I've confirmed as part of releasing 0.11 and updated accordingly.

**Comment by l2dy** [comment] 2020-12-02 05:39
> > Is the wrapped_json_correctness configuration missing Parsers_File
> 
> No, we have it defined [here](https://github.com/timberio/vector-test-harness/blob/ead8a2fc3544a110d72b467c5c544edbfe330c7e/cases/wrapped_json_correctness/ansible/config_files/td-agent-bit.parsers.conf)

You have the file, but it's not referenced from [td-agent-bit.conf](https://github.com/timberio/vector-test-harness/blob/ead8a2fc3544a110d72b467c5c544edbfe330c7e/cases/wrapped_json_correctness/ansible/config_files/td-agent-bit.conf).
