### ISSUE TITLE
internal_metrics: Expose `version` via metrics

### ISSUE THREAD

**Issue by guusvw** [timberio/vector#8120] opened 2021-07-02 07:52 UTC
### Current Vector Version

```
0.14.0
```

### Use-cases

Having a metric which expose the version of the vector agent to follow rolling-upgrades via metrics.

### Proposal

It would be nice to have an internal metric which expose the running version of the vector agent as metric.
This is by default done via a counter named `version` which is set to `1` and has a dimension with the current version.

**Comment by guusvw** [comment] 2021-07-02 09:42
Or adding it as dimension to the `uptime_seconds` metric

**Comment by jszwedko** [comment] 2021-07-06 15:54
Hi @guusvw ! Thanks for reporting. I think this is a duplicate of https://github.com/timberio/vector/issues/7364 . I'll close it in-lieu of that one, but feel free to re-open if I'm misunderstanding.

**Closed by jszwedko** 2021-07-06 15:54 UTC
Labels: type: enhancement

**Comment by guusvw** [comment] 2021-07-06 15:57
Ah @jszwedko, you're completely right, I thought I searched for other duplicates. Thanks 🙏
