### ISSUE TITLE
Journald wrong ouput of special character

### ISSUE THREAD

**Issue by SvenMarquardt5772** [timberio/vector#2601] opened 2020-05-14 10:28 UTC
We are using the journald source and the cloudwatch sink. 
Journalctl outputs the following

>{ "__CURSOR" : "s=c1579d290c0e4fa2bffa567a78a826d7;i=b844;b=c3d6c9e28e5d45dab29a29fcf52115ae;m=1100abb9a2;t=5a598d8ab4c04;x=1f1e44b582ad902d", "__REALTIME_TIMESTAMP" : "1589450772270084", "__MONOTONIC_TIMESTAMP" : "73025698210", "_BOOT_ID" : "c3d6c9e28e5d45dab29a29fcf52115ae", "_TRANSPORT" : "stdout", "_STREAM_ID" : "5ed20a0bade74d878c7907e8bda637da", "PRIORITY" : "6", "SYSLOG_FACILITY" : "3", "SYSLOG_IDENTIFIER" : "ipanema-presentation", "_PID" : "12865", "_UID" : "1001", "_GID" : "1001", "_CAP_EFFECTIVE" : "0", "_SYSTEMD_CGROUP" : "/system.slice/ipanema.service", "_SYSTEMD_UNIT" : "ipanema.service", "_SYSTEMD_SLICE" : "system.slice", "_MACHINE_ID" : "ded64cbff86f478990a3dfbb63a8d238", "_HOSTNAME" : "ip-172-16-5-59.eu-central-1.compute.internal", "_COMM" : "java", "_EXE" : "/usr/lib/jvm/jdk-11.0.2/bin/java", "_CMDLINE" : "java -server -XX:+CMSClassUnloadingEnabled -XX:+UseG1GC -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp/heapdump.hprof -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -XX:+UseStringDeduplication -XX:MaxHeapFreeRatio=70 -XX:MinHeapFreeRatio=40 -Duser.timezone=Europe/Berlin --add-modules java.sql -Drelease=1.287.26-bugfix-1017-SNAPSHOT -Xms1G -XX:MaxRAMPercentage=80 -classpath /application/Ipanema/lib/ipanema-presentation-1.287.26-bugfix-1017-SNAPSHOT.jar:/application/Ipanema/lib/ipanema-module-continuoustests-0.0.1.jar:/application/Ipanema/lib/ipanema-module-customerfeedreader-0.0.1.jar:/application/Ipanema/lib/ipanema-module-acemail-0.0.1.jar:/application/Ipanema/lib/ipanema-module-responseprocessor-0.0.1.jar:/application/Ipanema/lib/ipanema-module-eventtrigger-0.0.1.jar:/application/Ipanema/lib/ipanema-module-sendpush-0.0.1.jar:/application/Ipanema/lib/ipanema-module-event-0.0.1.jar:/application/Ipanema/lib/ipanema-module-productimport-0.0.1.jar:/application/Ipanema/lib/ipanema-module-servicefeedreader-0.0.1.jar:/application/Ipanema/lib/ipanema-module-campaignreader-0.0.1.jar:/application/Ipanema/lib/ipanema-module-archive-0.0.1.jar:/application/Ipanema/lib/ipanema-module-adobesupport-0.0.1.jar:/application/Ipanema/lib/ipanema-module-sftpcopyjobs-0.0.1.jar:/application/Ipanema/lib/ipanema-module-registerpush-0.0.1.jar:/application/Ipanema/lib/ipanema-module-packageadministration-0.0.1.jar:/application/Ipanema/lib/ipanema-module-presentationlogic-0.0.1.jar:/application/Ipanema/lib/ipanema-module-receivermanager-0.0.1.jar:/application/Ipanema/lib/ipanema-module-smalljobs-0.0.1.jar:/application/Ipanema/lib/ipanema-module-spoc-0.0.1.jar:/application/Ipanema/lib/ipanema-module-retailer-0.0.1.jar:/application/Ipanema/lib/ipanema-module-linkenrichment-0.0.1.jar:/application/Ipanema/lib/ipanema-module-genericexport-0.0.1.jar:/application/Ipanema/lib/ipanema-module-system-analysis-0.0.1.jar:/application/Ipanema/lib/ipanema-module-javascript-0.0.1.jar:/application/Ipanema/lib/ipanema-business-0.0.1.jar:/application/Ipanema/lib/ipanema-module-cis-benchmark-0.0.1.jar:/application/Ipanema/lib/ipanema-persistence-0.0.1.jar:/application/Ipanema/lib/ipanema-module-heartbeat-0.0.1.jar:/application/Ipanema/lib/ipanema-module-send-reporting-mail-0.0.1.jar:/application/Ipanema/lib/ipanema-module-cloudwatch-0.0.1.jar:/application/Ipanema/lib/ipanema-module-invoice-0.0.1.jar:/application/Ipanema/lib/ipanema-core-0.0.1.jar:/application/Ipanema/lib/hmac-auth-client-1.2.9.jar:/application/Ipanema/lib/spring-data-mongodb-2.1.10.RELEASE.jar:/application/Ipanema/lib/spring-data-rest-webmvc-3.1.10.RELEASE.jar:/application/Ipanema/lib/spring-data-rest-core-3.1.10.RELEASE.jar:/application/Ipanema/lib/spring-hateoas-0.25.2.RELEASE.jar:/application/Ipanema/lib/spring-webmvc-5.1.9.RELEASE.jar:/application/Ipanema/lib/hmac-auth-common-1.2.9.jar:/application/Ipanema/lib/spring-plugin-core-1.2.0.RELEASE.jar:/application/Ipanema/lib/spring-context-5.1.9.RELEASE.jar:/application/Ipanema/lib/spring-web-5.1.9.RELEASE.jar:/application/Ipanema/lib/spring-aop-5.1.9.RELEASE.jar:/application/Ipanema/lib/spring-aspects-5.1.9.RELEASE.jar:/application/Ipanema/lib/spring-tx-5.1.9.RELEASE.jar:/application/Ipanema/lib/spring-data-commons-2.1.10.RELEASE.jar:/application/Ipanema/lib/spring-beans-5.1.9.RELEASE.jar:/application/Ipanema/lib/spring-test-5.1.9.RELEASE.jar:/application/Ipanema/lib/logback-json-classic-0.1.5.jar:/application/Ipanema/lib/logback-classic-1.2.3.jar:/application/Ipanema/lib/logback-jackson-0.1.5.jar:/application/Ipanema/lib/logstash-logback-encoder-6.1.jar:/application/Ipanema/lib/java-jwt-3.8.2.jar:/application/Ipanema/lib/vaadin-charts-4.0.1.jar:/application/Ipanema/lib/vaadin-charts-model-4.0.1.jar:/application/Ipanema/lib/aws-java-sdk-ec2-1.11.618.jar:/application/Ipanema/lib/s3fs-2.2.2.jar:/application/Ipanema/lib/aws-java-sdk-s3-1.11.618.jar:/application/Ipanema/lib/aws", "MESSAGE" : "INFO  [Timer-3]: CisBenchmarkDataProvider:174 - Es wurden 0 regelverst\uffffffc3\uffffffb6\uffffffc3\uffffff9fe gefunden" }

And this is the messaging we are receiving in Cloudwatch

> {"_STREAM_ID":"6931307bcb984793b9e00b89d126877f","host":"ip-172-16-5-88.eu-central-1.compute.internal","message":"INFO [Timer-3]: CisBenchmarkDataProvider:174 - Es wurden 0 regelverst�ffc3�ffb6�ffc3�ff9fe gefunden","source_type":"journald"}

Is this a problem with journalctl described [here](https://vector.dev/docs/reference/sources/journald/#non-ascii-messages)? I already talked about this in gitter and was asked to open an issue here.

**Comment by bruceg** [comment] 2020-05-14 16:15
This is a different pattern than the one you reference (and . In the previously seen issue, the message would be shown as an array of bytes, ie `[73, 78, 70, …]` In this case, the message from journald is garbled, and I'm not sure what we can do with it.

The data here is represented as JSON, which is either ASCII or UTF-8 encoded. It contains escape sequences like `\uffffffc3`. The JSON parser sees the `\u` and interprets the next four hex characters as a Unicode character (as specified in the JSON standard). In this case, that is `\uffff`, which is not a valid Unicode character, hence the `�` mark above. This is then followed by the rest of the characters, so `ffc3`. Dropping the leading `ffff` doesn't work either, as `\uffc3` is `ￃ` which doesn't make sense in this context as well. It doesn't appear to be a valid UTF-8 byte sequence neither, so I'm stumped what happened here without more information.

Do you happen to know what the original text was for this message (complete with Germanic accented characters, I presume)?

**Comment by bruceg** [comment] 2020-05-14 16:23
Apparently `c3 b6` interpreted as hex digits *is* valid UTF-8 for `ö`, which does makes the message `"INFO [Timer-3]: CisBenchmarkDataProvider:174 - Es wurden 0 regelverstöße gefunden"`

That still doesn't explain what journald/journalctl is doing to produce those JSON sequences.

**Comment by SvenMarquardt5772** [comment] 2020-05-15 06:38
Maybe I should ask this in the systemd maillinglist then?

**Comment by bruceg** [comment] 2020-05-15 15:30
Yes, I'm thinking this looks like a journald issue, though I'm not sure what. Somewhere between your program outputting valid UTF-8 and journalctl giving us the JSON data the valid UTF-8 bytes were interpreted as signed binary characters and output as invalid Unicode escapes. This possibly may be something as simple as `$CHARSET` being set incorrectly somewhere (or unset), but in any case, the JSON provided to Vector by journalctl is bogus.

**Comment by binarylogic** [comment] 2020-05-18 14:24
Hi @SvenMarquardt5772, I'm closing this as it seems the issue is outside of Vector. Please let us know if that is not the case.

**Closed by binarylogic** 2020-05-18 14:24 UTC
Labels: source: journald, type: help
