### ISSUE TITLE
Failing publish docs workflow

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#5448] opened 2020-12-09 00:18 UTC
It looks like the `publish-docs.yml` workflow is failing on master: https://github.com/timberio/vector/runs/1520820433?check_suite_focus=true

```
  TSError: ⨯ Unable to compile TypeScript:
Error:   gatsby/source-nodes/vector-component/index.ts(3,28): error TS2307: Cannot find   module '../../../files/generated/cue.json' or its corresponding type declarat  ions.
Error:   gatsby/source-nodes/vector-component/index.ts(4,30): error TS2307: Cannot find   module '../../../files/generated/cue.types' or its corresponding type declara  tions.
```

**Comment by lucperkins** [comment] 2020-12-09 03:53
Closing as a duplicate of #5419

**Closed by lucperkins** 2020-12-09 03:53 UTC
Labels: type: bug
