### ISSUE TITLE
Negative throughput from `vector top`

### ISSUE THREAD

**Issue by spencergilbert** [timberio/vector#5319] opened 2020-12-01 19:37 UTC
### Vector Version

```
vector 0.11.0 (gafc64e5 x86_64-unknown-linux-gnu 2020-12-01)
```

### Vector Configuration File

```toml
# Data dir is location controlled at the `DaemonSet`.
data_dir = "/vector-data-dir"

[api]
enabled = true

[log_schema]
host_key = "host"
message_key = "message"
source_type_key = "source_type"
timestamp_key = "timestamp"

[sources.internal_metrics]
type = "internal_metrics"

# Ingest logs from Kubernetes.
[sources.kubernetes_logs]
type = "kubernetes_logs"

[sources.json_logs]
type = "file"
include = ["/var/log/kube-audit/*.json", "/var/lib/rancher/rke/log/*.log"]

[sources.system_logs]
type = "file"
include = ["/var/log/syslog*", "/var/log/auth.log*"]

[transforms.json_parser]
type = "json_parser"
inputs = ["json_logs"]
drop_invalid = true

[sinks.vector]
type = "vector"
inputs = ["kubernetes_logs","json_parser","system_logs"]
address = "vector-aggregator:9000"

[sinks.prometheus]
type = "prometheus_exporter"
inputs = ["internal_metrics"]
address = "0.0.0.0:9598"
default_namespace = "agent"
```

### Expected Behavior

Greater than 0 throughput

### Actual Behavior

![image](https://user-images.githubusercontent.com/11903873/100787046-0b967500-33e1-11eb-92f7-b43fe6e65504.png)

Negative throughput reported

I'm going to try some tests and see if it happens on other sources aside from `file`

**Comment by spencergilbert** [comment] 2020-12-01 20:30
@leebenson I don't see this happening on anything but the `file` source

**Comment by leebenson** [comment] 2020-12-02 07:23
cc @lukesteensen

**Comment by leebenson** [comment] 2020-12-16 13:36
We could set a lower bound of zero on displaying metrics in top, but I think that might be masking some unintended behaviour in the file source. I'm not super familiar with what should be done there, so assigning this to you @lukesteensen if you don't mind tackling this.

**Comment by lukesteensen** [comment] 2020-12-16 15:47
Yep, sorry for the delay, but I'll definitely be taking a look at this today!

**Comment by spencergilbert** [comment] 2020-12-16 17:03
@lukesteensen please let me know if I can share or help with anything else here

**Comment by lukesteensen** [comment] 2020-12-16 22:05
Well, good news in that the cause is pretty darn simple and there's nothing wrong with the file source. 

We calculate these throughput values here: https://github.com/timberio/vector/blob/e8d00b720363c7d47edf770d2ad1355b9065223f/src/api/schema/metrics/mod.rs#L349-L359

So we cache previous values based on the `component_name` tag and then subtract the previous value from the new one to get the difference over the interval. Seems reasonable and should give positive numbers given counters that go up.

The issue actually shows up because the file source provides more detailed metrics. Instead of one counter for the whole component, it adds an additional `file` tag that results in one counter per file. With just one cached value for the whole component, we end up looking at the difference between unrelated counters and get nonsense throughput values.

To fix this, and generally to handle metrics more granular than component-level, it seems like we'll need to restructure things a bit such that we have a chance to operate on metrics snapshots as a whole. Then we can simply add up all the counters per component name per snapshot and cache that result to compare with next time around.

That assumes that metrics don't age out, which is something we should verify. If they do, I think we'll need to keep whole snapshots around and do the comparison based on metrics present in both.

**Comment by spencergilbert** [comment] 2020-12-16 23:16
@lukesteensen sorry for a late update - but I also just caught it on a vector sink:
![image](https://user-images.githubusercontent.com/11903873/102417949-c53d3a80-3fca-11eb-9470-326e78d329ed.png)

**Comment by lukesteensen** [comment] 2020-12-16 23:52
Ah, interesting. In that case, it looks like the vector sink is _sometimes_ adding a `mode = "tcp"` tag and sometimes not, which is definitely wrong. That probably has something to do with it reusing some of the socket sink internals and a potential double count somewhere.

**Comment by leebenson** [comment] 2020-12-17 08:36
Thanks for looking into this, @lukesteensen. Makes sense. I'll update the API helpers to aggregate on the component_name rather than just looking at the first.

Some of this will likely cross paths with #5402, which is tasked with expanding the `Component` related schema to accommodate vendor-specific metrics.

**Comment by leebenson** [comment] 2020-12-23 20:47
@spencergilbert, the fix for this should now be in master, via https://github.com/timberio/vector/pull/5645. Closing, but feel free to re-open if you still spot this happening.

**Closed by leebenson** 2020-12-23 20:47 UTC
Labels: domain: cli, domain: observability, type: bug
