### ISSUE TITLE
 ERROR vector::topology: Failed to gracefully shut down in time. Killing components. components="out"

### ISSUE THREAD

**Issue by mutayoba5** [timberio/vector#6859] opened 2021-03-23 06:02 UTC
The error(above as the title) happens when I run ``` vector --config ./vector.toml ```

Here is my vector.toml 
```
[sources.generate_syslog]
  type = "generator"
  format = "syslog"
  count = 1000000

[transforms.remap_syslog]
  inputs = [ "generate_syslog"]
  type = "remap"
  source = '''
    structured = parse_syslog!(.message)
    . = merge(., structured)
  '''

[sinks.out]
request.concurrency = "adaptive"
type = "aws_s3"
inputs = [ "remap_syslog" ]
bucket = "test"
compression = "x"
region = "us-x-x"

# Batch
  batch.max_bytes = 100000000 # optional, default, bytes
  batch.timeout_secs = 300 # optional, default, seconds

  [sinks.out.encoding]
  codec = "ndjson"

```
I have removed some information and replaced it with `x`. Also my data does get shipped without an loosing data mid-stream.

**Comment by binarylogic** [comment] 2021-03-23 13:04
@ktff this looks like a pretty simple config, I'm curious if you can reproduce?

**Comment by ktff** [comment] 2021-03-24 15:25
@binarylogic it is reproducible, and it's a strange one, it happens in release mode but not in debug.

**Comment by ktff** [comment] 2021-07-25 11:04
So the chain of causes is:
* `vector` isn't shutting down because
* `aws_s3` sink isn't shutting down because
* it's retrying requests because
* basically all of them timed out because
* timeout of 60sec is too low because
* the timeout starts when the sink starts sending so depending on how fast or slow we send the data the actual timeout will be that much shorter. And in this case it takes a while to send all of the data so the timeout expires even before we are done sending the data.

This is also affecting other sinks that are using the same internal `TowerRequestSettings`, but a combination of things need to be for this bug too manifest.

### Solution
So if we start measuring timeout when we are done with sending the request this should be fixed, so I'll look into it. Alternatively, a quick fix for users is to increase `request.timeout_secs` and/or use `compression = "gzip"`

**Comment by ktff** [comment] 2021-07-26 10:09
There are multiple things that can be done independently:
1. > So if we start measuring timeout when we are done with sending the request

   This is doable with [`hyper-timeout`](https://crates.io/crates/hyper-timeout) crate which enables us to set timeout between individual read/write calls, but instead of using configured timeout for this we can use other value, like 20sec, which we can optionally expose as a configurable option `request.read/write_timeout_secs`. For this to have any effect the default value for `request.timeout_secs` should also be increased. And while we are it, #5858 can also be done in this way.

2. When warning that `Request timed out` also suggest how to fix it by increasing `request.timeout_secs`, decreasing `batch.max_bytes`, and/or using `compression`.

3.  Modifying our sink request retry layer to accept shutdown signal on which it would stop retrying requests. 

We can do 2. and 3. point under this issue while 1. would be better served in it's own issue. 

cc. @jszwedko

**Comment by jszwedko** [comment] 2021-07-26 19:37
Thanks for investigating this @ktff . I can see why this would happen given the `aws_s3` sink is often configured with a longer flush interval than 60s, the shutdown grace period.

An alternative might be to, on shutdown signal, flush the batches even if they aren't full. Would that make sense? We'd want to document this behavior of course.

**Comment by ktff** [comment] 2021-07-27 13:06
@jszwedko 
>  I can see why this would happen given the aws_s3 sink is often configured with a longer flush interval than 60s, the shutdown grace period.

That isn't a problem, since 

>  on shutdown signal, flush the batches even if they aren't full.

is the current behavior. 

The issue is that the sink is stuck in a retry loop for those requests that take longer to send then the timeout, since retrying those will always "fail".

**Comment by jszwedko** [comment] 2021-07-28 21:43
@ktff aha, I see. So the batch itself takes longer than the 60s to flush? Thanks for explaining.

In that case, I agree with you that we should probably not be retrying when shutting down. Would that be sufficient to resolve this?

**Comment by ktff** [comment] 2021-07-30 16:32
@jszwedko 
> So the batch itself takes longer than the 60s to flush? 

Yep, but it doesn't need to be longer than 60s, aws s3 has a few seconds of latency when responding with OK.

> we should probably not be retrying when shutting down. Would that be sufficient to resolve this?

Probably not since flushing can still stall the shutdown so if it takes longer than 60s it will stall. But there is not really anything that we can do about it, since the behavior is correct and the configuration is at fault, besides document the behavior in the warning and  `batch.max_bytes` option.

**Comment by jszwedko** [comment] 2021-07-30 16:56
> Probably not since flushing can still stall the shutdown so if it takes longer than 60s it will stall. But there is not really anything that we can do about it, since the behavior is correct and the configuration is at fault, besides document the behavior in the warning and `batch.max_bytes` option.

👍 stalling seems OK as long as it actually exits after the 60s even if the flush didn't complete.

**Comment by ktff** [comment] 2021-07-30 16:58
It exits even as it's now, so yes it will exit.

**Comment by jszwedko** [comment] 2021-07-30 17:02
Ah, great, then yes, that sounds right to me 😄

**Comment by ktff** [comment] 2021-08-11 16:05
I've pushed just the documentation changes. Since
> Modifying our sink request retry layer to accept shutdown signal on which it would stop retrying requests.

creates a different problem where a response that actually failed didn't retry because of the shutdown. Which besides potentially loosing data, that isn't happening with this issue, it would create a false sense that all of the events were flushed successfully since Vector shutdown gracefully.

It seems better to fail graceful shutdown if we can't guarantee that all events have been flushed.

Also we could decrease default value for `batch.max_bytes` to decrease the chance of this happening but that would reduce max throughput for default configuration so I think we should wait with this until it becomes obvious that a lot of users are experiencing this issue.

A long term solution is implementing 1. from https://github.com/timberio/vector/issues/6859#issuecomment-886563950

**Comment by jszwedko** [comment] 2021-08-11 17:02
Thanks @ktff . That makes sense. Just to confirm, Vector will always exit after the 60s grace period, correct?

**Comment by ktff** [comment] 2021-08-12 12:18
@jszwedko yes.

**Closed** 2021-08-13 13:28 UTC
Labels: type: bug, domain: shutdown
