### ISSUE TITLE
OSX unit tests segfault

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#4196] opened 2020-09-29 19:16 UTC
Discussed in discord: https://discordapp.com/channels/742820443487993987/746070604192415834/760546620559065148

Example: https://github.com/timberio/vector/pull/4193/checks?check_run_id=1183596467

Appears to have been introduced by https://github.com/timberio/vector/pull/4187

**Comment by leebenson** [comment] 2020-10-02 10:01
FWIW, I'm pretty sure I saw this even before #4187. It's especially hard to diagnose because it doesn't always happen, it happens even after _all_ tests have already passed, and I can't reproduce it locally in macOS 10.15.6.

There are similar issues on rust-lang:

- [FFI to C on MacOS causes segmentation fault (works on Ubuntu)](https://github.com/rust-lang/rust/issues/59202)
- [No issues on Linux, segfault on OS X (but only when building with `–release`)](https://users.rust-lang.org/t/no-issues-on-linux-segfault-on-os-x-but-only-when-building-with-release/17327/21)
- [https://users.rust-lang.org/t/segfaults-under-mac-os-with-multithreaded-code/18724](https://users.rust-lang.org/t/segfaults-under-mac-os-with-multithreaded-code/18724)
- [https://users.rust-lang.org/t/without-a-single-line-of-unsafe-code-i-am-getting-segfault-and-i-cant-figure-out-why-since-i-cant-stack-trace/40017](https://users.rust-lang.org/t/without-a-single-line-of-unsafe-code-i-am-getting-segfault-and-i-cant-figure-out-why-since-i-cant-stack-trace/40017)
- [https://github.com/rust-lang/rust/issues/73030](https://github.com/rust-lang/rust/issues/73030) (perhaps not directly related, but we were bitten by this in #4056 and removed related tests in #4050)
- [RUST_BACKTRACE on macOS can trigger crashes](https://github.com/rust-lang/rust/issues/71397)
- [Spurious LLDB segfault (signal 11)](https://github.com/rust-lang/rust/issues/45230)

Some of these are still open. Others were fixed in earlier Rust versions. Some may not be relevant. Some may be compiler issues, or due to external libs.

When using Travis, we could SSH into a test and perform some more in-depth testing againt the environment. I'm not sure what the options are for GH Actions. It's really hard to test because `make test` _never_ segfaults locally, with an identical toolchain.

One thing to note is that I saw segfaults (although not signal 11 specifically) when setting `codegen-units = 1`, when trying to work around a known LLVM issue with older macOS installations and parallel compilations, in environments other than macOS. In all cases, they were due to OOM errors. I'm wondering if this could also be memory pressure, although I don't know why it would specifically affect only macOS and not other OSs.

**Comment by leebenson** [comment] 2021-01-04 10:24
Do we have a recent example of where this is still surfacing? I haven't seen it personally for a while.

**Comment by jszwedko** [comment] 2021-01-04 14:54
I also haven't seen this in a quite a bit. I think we can close until it crops up again.

**Closed** 2021-01-04 15:13 UTC
Labels: domain: tests, type: bug
